"""Renderers for the two tool dialects plus the universal always-on surface.

Both per-domain files share one generated body (rule bullets with per-line ADR
citations, per ADR-0007); only the activation frontmatter differs — Copilot
takes ``applyTo:`` as a comma-joined string, Claude Code takes ``paths:`` as a
YAML list. The generated notice and the sentinel pair are defined once here as
module constants because they are load-bearing strings: deletion authority and
sentinel-region merging key on them exactly (ADR-0006).
"""

from __future__ import annotations

from app.projection.frontmatter import AdrRecord

#: Exact notice carried by every fully generated file; only files bearing this
#: string may ever be auto-deleted by the pipeline (ADR-0006).
GENERATED_NOTICE = (
    "<!-- generated by velocai projection from docs/adrs/ — do not edit; "
    "edit the source ADR and run `just project` -->"
)

#: Sentinel pair delimiting the generated region inside shared hand-authored
#: surfaces (`.github/copilot-instructions.md`).
SENTINEL_BEGIN = "<!-- velocai:begin generated -->"
SENTINEL_END = "<!-- velocai:end generated -->"

_STANDING_LINE = (
    "Rules below are projected from ADRs. Before modifying in-scope files, read "
    "the cited ADR in `docs/adrs/`; do not re-litigate accepted decisions."
)


def glob_union(records: list[AdrRecord]) -> list[str]:
    """Sorted, deduplicated union of the member records' scope globs."""

    return sorted({token for record in records for token in record.scope})


def _body(heading: str, records: list[AdrRecord]) -> str:
    """Shared generated body: heading, standing line, one cited bullet per rule."""

    bullets = "\n".join(f"- {record.rule} ({record.id})" for record in records)
    return f"# {heading}\n\n{_STANDING_LINE}\n\n{bullets}\n"


def render_copilot_domain(domain: str, records: list[AdrRecord]) -> str:
    """Render one `.github/instructions/<domain>.instructions.md` file."""

    apply_to = ",".join(glob_union(records))
    return (
        f'---\napplyTo: "{apply_to}"\n---\n'
        f"{GENERATED_NOTICE}\n\n{_body(f'{domain} rules', records)}"
    )


def render_claude_domain(domain: str, records: list[AdrRecord]) -> str:
    """Render one `.claude/rules/<domain>.md` file."""

    paths = "\n".join(f'  - "{token}"' for token in glob_union(records))
    return (
        f"---\npaths:\n{paths}\n---\n"
        f"{GENERATED_NOTICE}\n\n{_body(f'{domain} rules', records)}"
    )


def render_claude_universal(records: list[AdrRecord]) -> str:
    """Render `.claude/rules/universal.md` — no ``paths:``, so always loaded."""

    return f"{GENERATED_NOTICE}\n\n{_body('Universal rules', records)}"


def render_copilot_universal_block(records: list[AdrRecord]) -> str:
    """Render the sentinel-delimited block for `.github/copilot-instructions.md`.

    Hand-authored prose outside the sentinels survives regeneration; the block
    is the only region the pipeline owns in that file (ADR-0006).
    """

    return (
        f"{SENTINEL_BEGIN}\n{GENERATED_NOTICE}\n\n"
        f"{_body('Universal rules', records)}{SENTINEL_END}\n"
    )
